version: '3.8'
services:
  app:
    image: node_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '3000:3000'
    command: node app
    volumes:
    - .:/var/www/app:rw

