version: '3.8'
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '8080:8080'
    depends_on:
      - mongo
    volumes:
    - .:/var/www/app:rw

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
    - ./data:/data/db
    ports:
      - "27018:27017"

