version: '3.8'
services:
  app:
    restart: always
    build: .
    ports:
    - '8080:8080'
    depends_on:
      - mongo
    volumes:
    - .:/var/www/app:rw

  mongo:
    image: mongo
    restart: always
    volumes:
    - ./data:/data/db
    ports:
      - "27018:27017"

