version: '3.8'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
    - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
    - ./data:/data/db
    ports:
      - "27117:27017"

